{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":25250,"status":"ok","timestamp":1728304826838,"user":{"displayName":"Akhilesh Yelamali","userId":"05580659329514564688"},"user_tz":-330},"id":"sw1MzkF9qvkE","outputId":"ecc64766-ee2b-4ae6-b7fc-7c1cf9189fd5"},"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":4,"status":"ok","timestamp":1728304826838,"user":{"displayName":"Akhilesh Yelamali","userId":"05580659329514564688"},"user_tz":-330},"id":"Mm_a5yJkhwhm","outputId":"5bea1e63-fcb4-4d8f-dd39-1c0e59106be7"},"outputs":[{"output_type":"stream","name":"stdout","text":["/content/drive/MyDrive/CEVI_Final\n"]}],"source":["%cd /content/drive/MyDrive/CEVI_Final\n"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":263388,"status":"ok","timestamp":1728305115836,"user":{"displayName":"Akhilesh Yelamali","userId":"05580659329514564688"},"user_tz":-330},"id":"EZLoPsEtpv1z","outputId":"90b4bbcf-c27f-417a-aa71-083e845eb20c"},"outputs":[{"output_type":"stream","name":"stdout","text":["Obtaining file:///content/drive/MyDrive/CEVI_Final/sam\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Installing collected packages: segment_anything\n","  Running setup.py develop for segment_anything\n","Successfully installed segment_anything-1.0\n","/content/drive/MyDrive/CEVI_Final\n","Obtaining GroundingDINO from git+https://github.com/IDEA-Research/GroundingDINO.git@main#egg=GroundingDINO\n","  Updating ./src/groundingdino clone (to revision main)\n","  Running command git fetch -q --tags\n","  Running command git reset --hard -q 856dde20aee659246248e20734ef9ba5214f5e44\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (2.4.1+cu121)\n","Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (0.19.1+cu121)\n","Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (4.44.2)\n","Collecting addict (from GroundingDINO)\n","  Downloading addict-2.4.0-py3-none-any.whl.metadata (1.0 kB)\n","Collecting yapf (from GroundingDINO)\n","  Downloading yapf-0.40.2-py3-none-any.whl.metadata (45 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m45.4/45.4 kB\u001b[0m \u001b[31m2.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting timm (from GroundingDINO)\n","  Downloading timm-1.0.9-py3-none-any.whl.metadata (42 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m42.4/42.4 kB\u001b[0m \u001b[31m1.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (1.26.4)\n","Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (4.10.0.84)\n","Collecting supervision>=0.22.0 (from GroundingDINO)\n","  Downloading supervision-0.24.0-py3-none-any.whl.metadata (14 kB)\n","Requirement already satisfied: pycocotools in /usr/local/lib/python3.10/dist-packages (from GroundingDINO) (2.0.8)\n","Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from supervision>=0.22.0->GroundingDINO) (0.7.1)\n","Requirement already satisfied: matplotlib>=3.6.0 in /usr/local/lib/python3.10/dist-packages (from supervision>=0.22.0->GroundingDINO) (3.7.1)\n","Requirement already satisfied: pillow>=9.4 in /usr/local/lib/python3.10/dist-packages (from supervision>=0.22.0->GroundingDINO) (10.4.0)\n","Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.10/dist-packages (from supervision>=0.22.0->GroundingDINO) (6.0.2)\n","Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from supervision>=0.22.0->GroundingDINO) (1.13.1)\n","Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (from timm->GroundingDINO) (0.24.7)\n","Requirement already satisfied: safetensors in /usr/local/lib/python3.10/dist-packages (from timm->GroundingDINO) (0.4.5)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (3.16.1)\n","Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (4.12.2)\n","Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (1.13.3)\n","Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (3.3)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (3.1.4)\n","Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->GroundingDINO) (2024.6.1)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers->GroundingDINO) (24.1)\n","Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers->GroundingDINO) (2024.9.11)\n","Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers->GroundingDINO) (2.32.3)\n","Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers->GroundingDINO) (0.19.1)\n","Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers->GroundingDINO) (4.66.5)\n","Requirement already satisfied: importlib-metadata>=6.6.0 in /usr/local/lib/python3.10/dist-packages (from yapf->GroundingDINO) (8.4.0)\n","Requirement already satisfied: platformdirs>=3.5.1 in /usr/local/lib/python3.10/dist-packages (from yapf->GroundingDINO) (4.3.6)\n","Requirement already satisfied: tomli>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from yapf->GroundingDINO) (2.0.1)\n","Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=6.6.0->yapf->GroundingDINO) (3.20.2)\n","Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (1.3.0)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (0.12.1)\n","Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (4.54.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (1.4.7)\n","Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (3.1.4)\n","Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (2.8.2)\n","Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->GroundingDINO) (2.1.5)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->GroundingDINO) (3.3.2)\n","Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->GroundingDINO) (3.10)\n","Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->GroundingDINO) (2.2.3)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->GroundingDINO) (2024.8.30)\n","Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->GroundingDINO) (1.3.0)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6.0->supervision>=0.22.0->GroundingDINO) (1.16.0)\n","Downloading supervision-0.24.0-py3-none-any.whl (158 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m158.2/158.2 kB\u001b[0m \u001b[31m10.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading addict-2.4.0-py3-none-any.whl (3.8 kB)\n","Downloading timm-1.0.9-py3-none-any.whl (2.3 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.3/2.3 MB\u001b[0m \u001b[31m44.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading yapf-0.40.2-py3-none-any.whl (254 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m254.7/254.7 kB\u001b[0m \u001b[31m21.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: addict, yapf, supervision, timm, GroundingDINO\n","  Running setup.py develop for GroundingDINO\n","Successfully installed GroundingDINO-0.1.0 addict-2.4.0 supervision-0.24.0 timm-1.0.9 yapf-0.40.2\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)\n","Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (4.10.0.84)\n","Requirement already satisfied: pycocotools in /usr/local/lib/python3.10/dist-packages (2.0.8)\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)\n","Collecting Pillow==9.2.0\n","  Downloading Pillow-9.2.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)\n","Requirement already satisfied: scikit-image in /usr/local/lib/python3.10/dist-packages (0.24.0)\n","Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.0)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)\n","Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.54.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.1)\n","Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.4)\n","Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)\n","Requirement already satisfied: scipy>=1.9 in /usr/local/lib/python3.10/dist-packages (from scikit-image) (1.13.1)\n","Requirement already satisfied: networkx>=2.8 in /usr/local/lib/python3.10/dist-packages (from scikit-image) (3.3)\n","Requirement already satisfied: imageio>=2.33 in /usr/local/lib/python3.10/dist-packages (from scikit-image) (2.35.1)\n","Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.10/dist-packages (from scikit-image) (2024.9.20)\n","Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.10/dist-packages (from scikit-image) (0.4)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\n","Downloading Pillow-9.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.2 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.2/3.2 MB\u001b[0m \u001b[31m38.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: Pillow\n","  Attempting uninstall: Pillow\n","    Found existing installation: pillow 10.4.0\n","    Uninstalling pillow-10.4.0:\n","      Successfully uninstalled pillow-10.4.0\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","supervision 0.24.0 requires pillow>=9.4, but you have pillow 9.2.0 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed Pillow-9.2.0\n","Collecting gradio==3.39.0\n","  Downloading gradio-3.39.0-py3-none-any.whl.metadata (17 kB)\n","Collecting zip\n","  Downloading zip-0.0.2.tar.gz (3.0 kB)\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (5.2.0)\n","Collecting ffmpeg==1.4\n","  Downloading ffmpeg-1.4.tar.gz (5.1 kB)\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting aiofiles<24.0,>=22.0 (from gradio==3.39.0)\n","  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)\n","Requirement already satisfied: aiohttp~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.10.8)\n","Requirement already satisfied: altair<6.0,>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (4.2.2)\n","Collecting fastapi (from gradio==3.39.0)\n","  Downloading fastapi-0.115.0-py3-none-any.whl.metadata (27 kB)\n","Collecting ffmpy (from gradio==3.39.0)\n","  Downloading ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)\n","Collecting gradio-client>=0.3.0 (from gradio==3.39.0)\n","  Downloading gradio_client-1.3.0-py3-none-any.whl.metadata (7.1 kB)\n","Collecting httpx (from gradio==3.39.0)\n","  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)\n","Requirement already satisfied: huggingface-hub>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (0.24.7)\n","Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.1.4)\n","Requirement already satisfied: markdown-it-py>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py[linkify]>=2.0.0->gradio==3.39.0) (3.0.0)\n","Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.1.5)\n","Requirement already satisfied: matplotlib~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.7.1)\n","Collecting mdit-py-plugins<=0.3.3 (from gradio==3.39.0)\n","  Downloading mdit_py_plugins-0.3.3-py3-none-any.whl.metadata (2.8 kB)\n","Requirement already satisfied: numpy~=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (1.26.4)\n","Collecting orjson~=3.0 (from gradio==3.39.0)\n","  Downloading orjson-3.10.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (50 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m50.4/50.4 kB\u001b[0m \u001b[31m1.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (24.1)\n","Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.2.2)\n","Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (9.2.0)\n","Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.9.2)\n","Collecting pydub (from gradio==3.39.0)\n","  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)\n","Collecting python-multipart (from gradio==3.39.0)\n","  Downloading python_multipart-0.0.12-py3-none-any.whl.metadata (1.9 kB)\n","Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (6.0.2)\n","Requirement already satisfied: requests~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.32.3)\n","Collecting semantic-version~=2.0 (from gradio==3.39.0)\n","  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)\n","Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (4.12.2)\n","Collecting uvicorn>=0.14.0 (from gradio==3.39.0)\n","  Downloading uvicorn-0.31.0-py3-none-any.whl.metadata (6.6 kB)\n","Collecting websockets<12.0,>=10.0 (from gradio==3.39.0)\n","  Downloading websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n","Collecting Flask-Admin>=1.0.4 (from zip)\n","  Downloading Flask_Admin-1.6.1-py3-none-any.whl.metadata (5.8 kB)\n","Collecting Flask-Bootstrap>=2.2.2-1 (from zip)\n","  Downloading Flask-Bootstrap-3.3.7.1.tar.gz (456 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m456.4/456.4 kB\u001b[0m \u001b[31m19.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting Flask-Cache>=0.10.1 (from zip)\n","  Downloading Flask-Cache-0.13.1.tar.gz (45 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m45.8/45.8 kB\u001b[0m \u001b[31m4.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting Flask-FlatPages>=0.3 (from zip)\n","  Downloading Flask_FlatPages-0.8.2-py3-none-any.whl.metadata (2.6 kB)\n","Collecting Flask-Gravatar>=0.2.4 (from zip)\n","  Downloading Flask_Gravatar-0.5.0-py2.py3-none-any.whl.metadata (5.4 kB)\n","Collecting Flask-Login>=0.1.3 (from zip)\n","  Downloading Flask_Login-0.6.3-py3-none-any.whl.metadata (5.8 kB)\n","Collecting Flask-Mail>=0.7.4 (from zip)\n","  Downloading flask_mail-0.10.0-py3-none-any.whl.metadata (2.1 kB)\n","Collecting Flask-PyMongo>=0.2.1 (from zip)\n","  Downloading Flask_PyMongo-2.3.0-py2.py3-none-any.whl.metadata (1.4 kB)\n","Collecting Flask-Restless>=0.9.1 (from zip)\n","  Downloading Flask-Restless-0.17.0.tar.gz (42 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m42.7/42.7 kB\u001b[0m \u001b[31m3.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting Flask-SQLAlchemy>=0.16 (from zip)\n","  Downloading flask_sqlalchemy-3.1.1-py3-none-any.whl.metadata (3.4 kB)\n","Collecting Flask-Themes>=0.1.3 (from zip)\n","  Downloading Flask-Themes-0.1.3.tar.gz (9.7 kB)\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting Flask-Uploads>=0.1.3 (from zip)\n","  Downloading Flask-Uploads-0.2.1.tar.gz (7.6 kB)\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting Flask-WTF>=0.8.2 (from zip)\n","  Downloading flask_wtf-1.2.1-py3-none-any.whl.metadata (3.4 kB)\n","Requirement already satisfied: Flask>=0.9 in /usr/local/lib/python3.10/dist-packages (from zip) (2.2.5)\n","Collecting frozen-flask (from zip)\n","  Downloading frozen_flask-1.0.2-py3-none-any.whl.metadata (5.1 kB)\n","Requirement already satisfied: Markdown>=2.2.1 in /usr/local/lib/python3.10/dist-packages (from zip) (3.7)\n","Requirement already satisfied: SQLAlchemy>=0.8.0b2 in /usr/local/lib/python3.10/dist-packages (from zip) (2.0.35)\n","Requirement already satisfied: Sphinx>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from zip) (5.0.2)\n","Collecting WTForms>=1.0.3 (from zip)\n","  Downloading wtforms-3.1.2-py3-none-any.whl.metadata (5.3 kB)\n","Requirement already satisfied: Werkzeug>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from zip) (3.0.4)\n","Collecting argparse>=1.2.1 (from zip)\n","  Downloading argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)\n","Requirement already satisfied: blinker>=1.2 in /usr/lib/python3/dist-packages (from zip) (1.4)\n","Collecting bumpversion>=0.5.3 (from zip)\n","  Downloading bumpversion-0.6.0-py2.py3-none-any.whl.metadata (19 kB)\n","Requirement already satisfied: click>=6.3 in /usr/local/lib/python3.10/dist-packages (from zip) (8.1.7)\n","Collecting colorama>=0.3.7 (from zip)\n","  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)\n","Collecting coverage>=4.0 (from zip)\n","  Downloading coverage-7.6.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)\n","Requirement already satisfied: cryptography>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from zip) (43.0.1)\n","Collecting flake8>=2.4.1 (from zip)\n","  Downloading flake8-7.1.1-py2.py3-none-any.whl.metadata (3.8 kB)\n","Requirement already satisfied: networkx>=1.11 in /usr/local/lib/python3.10/dist-packages (from zip) (3.3)\n","Collecting pymongo>=2.5.1 (from zip)\n","  Downloading pymongo-4.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)\n","Requirement already satisfied: pytest>=2.8.3 in /usr/local/lib/python3.10/dist-packages (from zip) (7.4.4)\n","Requirement already satisfied: python-dateutil>=1.5 in /usr/local/lib/python3.10/dist-packages (from zip) (2.8.2)\n","Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from zip) (1.16.0)\n","Collecting tox>=2.1.1 (from zip)\n","  Downloading tox-4.21.2-py3-none-any.whl.metadata (5.0 kB)\n","Collecting watchdog>=0.8.3 (from zip)\n","  Downloading watchdog-5.0.3-py3-none-manylinux2014_x86_64.whl.metadata (41 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m41.9/41.9 kB\u001b[0m \u001b[31m3.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: wheel>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from zip) (0.44.0)\n","Collecting wsgiref>=0.1.2 (from zip)\n","  Downloading wsgiref-0.1.2.zip (37 kB)\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n","fatal: destination path 'Pytorch-Correlation-extension' already exists and is not an empty directory.\n","running install\n","/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n","!!\n","\n","        ********************************************************************************\n","        Please avoid running ``setup.py`` directly.\n","        Instead, use pypa/build, pypa/installer or other\n","        standards-based tools.\n","\n","        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n","        ********************************************************************************\n","\n","!!\n","  self.initialize_options()\n","/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.\n","!!\n","\n","        ********************************************************************************\n","        Please avoid running ``setup.py`` and ``easy_install``.\n","        Instead, use pypa/build, pypa/installer or other\n","        standards-based tools.\n","\n","        See https://github.com/pypa/setuptools/issues/917 for details.\n","        ********************************************************************************\n","\n","!!\n","  self.initialize_options()\n","running bdist_egg\n","running egg_info\n","writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO\n","writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt\n","writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt\n","writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt\n","/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.\n","  warnings.warn(msg.format('we could not find ninja.'))\n","reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'\n","adding license file 'LICENSE'\n","writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'\n","installing library code to build/bdist.linux-x86_64/egg\n","running install_lib\n","running build_py\n","running build_ext\n","/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (12.2) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.\n","  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))\n","/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.2\n","  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')\n","building 'spatial_correlation_sampler_backend' extension\n","x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE_CUDA -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation.o -std=c++17 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0\n","/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. \n","If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].\n","  warnings.warn(\n","/usr/local/cuda/bin/nvcc -DUSE_CUDA -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c Correlation_Module/correlation_cuda_kernel.cu -o build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++17\n","x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE_CUDA -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_sampler.o -std=c++17 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0\n","x86_64-linux-gnu-g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation.o build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_cuda_kernel.o build/temp.linux-x86_64-cpython-310/Correlation_Module/correlation_sampler.o -L/usr/local/lib/python3.10/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler_backend.cpython-310-x86_64-linux-gnu.so -lgomp\n","creating build/bdist.linux-x86_64/egg\n","creating build/bdist.linux-x86_64/egg/spatial_correlation_sampler\n","copying build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler\n","copying build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler/__init__.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler\n","copying build/lib.linux-x86_64-cpython-310/spatial_correlation_sampler_backend.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg\n","byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/spatial_correlation_sampler.py to spatial_correlation_sampler.cpython-310.pyc\n","byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/__init__.py to __init__.cpython-310.pyc\n","creating stub loader for spatial_correlation_sampler_backend.cpython-310-x86_64-linux-gnu.so\n","byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler_backend.py to spatial_correlation_sampler_backend.cpython-310.pyc\n","creating build/bdist.linux-x86_64/egg/EGG-INFO\n","copying Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO\n","copying Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n","copying Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n","copying Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n","copying Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n","writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt\n","zip_safe flag not set; analyzing archive contents...\n","__pycache__.spatial_correlation_sampler_backend.cpython-310: module references __file__\n","creating 'dist/spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it\n","removing 'build/bdist.linux-x86_64/egg' (and everything under it)\n","Processing spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg\n","creating /usr/local/lib/python3.10/dist-packages/spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg\n","Extracting spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg to /usr/local/lib/python3.10/dist-packages\n","Adding spatial-correlation-sampler 0.4.0 to easy-install.pth file\n","\n","Installed /usr/local/lib/python3.10/dist-packages/spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg\n","Processing dependencies for spatial-correlation-sampler==0.4.0\n","Searching for numpy==1.26.4\n","Best match: numpy 1.26.4\n","Adding numpy 1.26.4 to easy-install.pth file\n","detected new path './spatial_correlation_sampler-0.4.0-py3.10-linux-x86_64.egg'\n","Installing f2py script to /usr/local/bin\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for torch==2.4.1+cu121\n","Best match: torch 2.4.1+cu121\n","Adding torch 2.4.1+cu121 to easy-install.pth file\n","Installing convert-caffe2-to-onnx script to /usr/local/bin\n","Installing convert-onnx-to-caffe2 script to /usr/local/bin\n","Installing torchrun script to /usr/local/bin\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for fsspec==2024.6.1\n","Best match: fsspec 2024.6.1\n","Adding fsspec 2024.6.1 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for jinja2==3.1.4\n","Best match: jinja2 3.1.4\n","Adding jinja2 3.1.4 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for networkx==3.3\n","Best match: networkx 3.3\n","Adding networkx 3.3 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for sympy==1.13.3\n","Best match: sympy 1.13.3\n","Adding sympy 1.13.3 to easy-install.pth file\n","Installing isympy script to /usr/local/bin\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for typing-extensions==4.12.2\n","Best match: typing-extensions 4.12.2\n","Adding typing-extensions 4.12.2 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages/setuptools/_vendor\n","Searching for filelock==3.16.1\n","Best match: filelock 3.16.1\n","Adding filelock 3.16.1 to easy-install.pth file\n","detected new path './setuptools/_vendor'\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for MarkupSafe==2.1.5\n","Best match: MarkupSafe 2.1.5\n","Adding MarkupSafe 2.1.5 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Searching for mpmath==1.3.0\n","Best match: mpmath 1.3.0\n","Adding mpmath 1.3.0 to easy-install.pth file\n","\n","Using /usr/local/lib/python3.10/dist-packages\n","Finished processing dependencies for spatial-correlation-sampler==0.4.0\n","/content/drive/MyDrive/CEVI_Final\n"]}],"source":["!bash script/install.sh"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":9905,"status":"ok","timestamp":1728305163046,"user":{"displayName":"Akhilesh Yelamali","userId":"05580659329514564688"},"user_tz":-330},"id":"IiSQHytJp6ry","outputId":"2d71e364-58e9-4ce4-e77b-c8e05722e49c"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting gradio==3.39.0\n","  Using cached gradio-3.39.0-py3-none-any.whl.metadata (17 kB)\n","Collecting aiofiles<24.0,>=22.0 (from gradio==3.39.0)\n","  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)\n","Requirement already satisfied: aiohttp~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.10.8)\n","Requirement already satisfied: altair<6.0,>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (4.2.2)\n","Collecting fastapi (from gradio==3.39.0)\n","  Using cached fastapi-0.115.0-py3-none-any.whl.metadata (27 kB)\n","Collecting ffmpy (from gradio==3.39.0)\n","  Using cached ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)\n","Collecting gradio-client>=0.3.0 (from gradio==3.39.0)\n","  Using cached gradio_client-1.3.0-py3-none-any.whl.metadata (7.1 kB)\n","Collecting httpx (from gradio==3.39.0)\n","  Using cached httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)\n","Requirement already satisfied: huggingface-hub>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (0.24.7)\n","Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.1.4)\n","Requirement already satisfied: markdown-it-py>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py[linkify]>=2.0.0->gradio==3.39.0) (3.0.0)\n","Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.1.5)\n","Requirement already satisfied: matplotlib~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (3.7.1)\n","Collecting mdit-py-plugins<=0.3.3 (from gradio==3.39.0)\n","  Using cached mdit_py_plugins-0.3.3-py3-none-any.whl.metadata (2.8 kB)\n","Requirement already satisfied: numpy~=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (1.26.4)\n","Collecting orjson~=3.0 (from gradio==3.39.0)\n","  Using cached orjson-3.10.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (50 kB)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (24.1)\n","Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.2.2)\n","Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (9.2.0)\n","Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.9.2)\n","Collecting pydub (from gradio==3.39.0)\n","  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)\n","Collecting python-multipart (from gradio==3.39.0)\n","  Using cached python_multipart-0.0.12-py3-none-any.whl.metadata (1.9 kB)\n","Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (6.0.2)\n","Requirement already satisfied: requests~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (2.32.3)\n","Collecting semantic-version~=2.0 (from gradio==3.39.0)\n","  Using cached semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)\n","Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.39.0) (4.12.2)\n","Collecting uvicorn>=0.14.0 (from gradio==3.39.0)\n","  Using cached uvicorn-0.31.0-py3-none-any.whl.metadata (6.6 kB)\n","Collecting websockets<12.0,>=10.0 (from gradio==3.39.0)\n","  Using cached websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n","Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (2.4.3)\n","Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (1.3.1)\n","Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (24.2.0)\n","Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (1.4.1)\n","Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (6.1.0)\n","Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (1.13.1)\n","Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp~=3.0->gradio==3.39.0) (4.0.3)\n","Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.39.0) (0.4)\n","Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.39.0) (4.23.0)\n","Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.39.0) (0.12.1)\n","Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client>=0.3.0->gradio==3.39.0) (2024.6.1)\n","Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.39.0) (3.7.1)\n","Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.39.0) (2024.8.30)\n","Collecting httpcore==1.* (from httpx->gradio==3.39.0)\n","  Downloading httpcore-1.0.6-py3-none-any.whl.metadata (21 kB)\n","Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.39.0) (3.10)\n","Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.39.0) (1.3.1)\n","Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx->gradio==3.39.0)\n","  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.14.0->gradio==3.39.0) (3.16.1)\n","Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.14.0->gradio==3.39.0) (4.66.5)\n","Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.0.0->markdown-it-py[linkify]>=2.0.0->gradio==3.39.0) (0.1.2)\n","Requirement already satisfied: linkify-it-py<3,>=1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py[linkify]>=2.0.0->gradio==3.39.0) (2.0.3)\n","Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (1.3.0)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (0.12.1)\n","Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (4.54.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (1.4.7)\n","Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (3.1.4)\n","Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.39.0) (2.8.2)\n","INFO: pip is looking at multiple versions of mdit-py-plugins to determine which version is compatible with other requirements. This could take a while.\n","Collecting mdit-py-plugins<=0.3.3 (from gradio==3.39.0)\n","  Downloading mdit_py_plugins-0.3.2-py3-none-any.whl.metadata (2.8 kB)\n","  Downloading mdit_py_plugins-0.3.1-py3-none-any.whl.metadata (2.8 kB)\n","  Downloading mdit_py_plugins-0.3.0-py3-none-any.whl.metadata (2.8 kB)\n","  Downloading mdit_py_plugins-0.2.8-py3-none-any.whl.metadata (2.8 kB)\n","  Downloading mdit_py_plugins-0.2.7-py3-none-any.whl.metadata (2.8 kB)\n","  Downloading mdit_py_plugins-0.2.6-py3-none-any.whl.metadata (2.6 kB)\n","  Downloading mdit_py_plugins-0.2.5-py3-none-any.whl.metadata (2.6 kB)\n","INFO: pip is still looking at multiple versions of mdit-py-plugins to determine which version is compatible with other requirements. This could take a while.\n","  Downloading mdit_py_plugins-0.2.4-py3-none-any.whl.metadata (2.6 kB)\n","  Downloading mdit_py_plugins-0.2.3-py3-none-any.whl.metadata (2.6 kB)\n","  Downloading mdit_py_plugins-0.2.2-py3-none-any.whl.metadata (2.6 kB)\n","  Downloading mdit_py_plugins-0.2.1-py3-none-any.whl.metadata (2.6 kB)\n","  Downloading mdit_py_plugins-0.2.0-py3-none-any.whl.metadata (2.6 kB)\n","INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n","  Downloading mdit_py_plugins-0.1.0-py3-none-any.whl.metadata (2.6 kB)\n","Collecting markdown-it-py[linkify]>=2.0.0 (from gradio==3.39.0)\n","  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)\n","  Downloading markdown_it_py-2.2.0-py3-none-any.whl.metadata (6.8 kB)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio==3.39.0) (2024.2)\n","Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio==3.39.0) (2024.2)\n","Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.39.0) (0.7.0)\n","Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.39.0) (2.23.4)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests~=2.0->gradio==3.39.0) (3.3.2)\n","Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests~=2.0->gradio==3.39.0) (2.2.3)\n","Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from uvicorn>=0.14.0->gradio==3.39.0) (8.1.7)\n","Collecting starlette<0.39.0,>=0.37.2 (from fastapi->gradio==3.39.0)\n","  Downloading starlette-0.38.6-py3-none-any.whl.metadata (6.0 kB)\n","Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.39.0) (2023.12.1)\n","Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.39.0) (0.35.1)\n","Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==3.39.0) (0.20.0)\n","Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.10/dist-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify]>=2.0.0->gradio==3.39.0) (1.0.3)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio==3.39.0) (1.16.0)\n","Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->gradio==3.39.0) (1.2.2)\n","Downloading gradio-3.39.0-py3-none-any.whl (19.9 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m19.9/19.9 MB\u001b[0m \u001b[31m92.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading aiofiles-23.2.1-py3-none-any.whl (15 kB)\n","Downloading gradio_client-1.3.0-py3-none-any.whl (318 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m318.7/318.7 kB\u001b[0m \u001b[31m27.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading httpx-0.27.2-py3-none-any.whl (76 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m76.4/76.4 kB\u001b[0m \u001b[31m6.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading httpcore-1.0.6-py3-none-any.whl (78 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m78.0/78.0 kB\u001b[0m \u001b[31m8.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m84.5/84.5 kB\u001b[0m \u001b[31m8.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading mdit_py_plugins-0.3.3-py3-none-any.whl (50 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m50.5/50.5 kB\u001b[0m \u001b[31m4.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading orjson-3.10.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m141.9/141.9 kB\u001b[0m \u001b[31m13.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)\n","Downloading uvicorn-0.31.0-py3-none-any.whl (63 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m63.7/63.7 kB\u001b[0m \u001b[31m6.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m129.9/129.9 kB\u001b[0m \u001b[31m12.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading fastapi-0.115.0-py3-none-any.whl (94 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m94.6/94.6 kB\u001b[0m \u001b[31m9.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading ffmpy-0.4.0-py3-none-any.whl (5.8 kB)\n","Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)\n","Downloading python_multipart-0.0.12-py3-none-any.whl (23 kB)\n","Downloading h11-0.14.0-py3-none-any.whl (58 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m58.3/58.3 kB\u001b[0m \u001b[31m5.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading starlette-0.38.6-py3-none-any.whl (71 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m71.5/71.5 kB\u001b[0m \u001b[31m6.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: pydub, websockets, semantic-version, python-multipart, orjson, markdown-it-py, h11, ffmpy, aiofiles, uvicorn, starlette, mdit-py-plugins, httpcore, httpx, fastapi, gradio-client, gradio\n","  Attempting uninstall: markdown-it-py\n","    Found existing installation: markdown-it-py 3.0.0\n","    Uninstalling markdown-it-py-3.0.0:\n","      Successfully uninstalled markdown-it-py-3.0.0\n","  Attempting uninstall: mdit-py-plugins\n","    Found existing installation: mdit-py-plugins 0.4.2\n","    Uninstalling mdit-py-plugins-0.4.2:\n","      Successfully uninstalled mdit-py-plugins-0.4.2\n","Successfully installed aiofiles-23.2.1 fastapi-0.115.0 ffmpy-0.4.0 gradio-3.39.0 gradio-client-1.3.0 h11-0.14.0 httpcore-1.0.6 httpx-0.27.2 markdown-it-py-2.2.0 mdit-py-plugins-0.3.3 orjson-3.10.7 pydub-0.25.1 python-multipart-0.0.12 semantic-version-2.10.0 starlette-0.38.6 uvicorn-0.31.0 websockets-11.0.3\n"]}],"source":["  !pip install gradio==3.39.0"]},{"cell_type":"code","execution_count":9,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"bw1G4paDjL5-","outputId":"730ed3b3-83eb-4db1-df19-a5f823340d88","executionInfo":{"status":"ok","timestamp":1728305966334,"user_tz":-330,"elapsed":133467,"user":{"displayName":"Akhilesh Yelamali","userId":"05580659329514564688"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'\n","  warnings.warn(f\"Could not get documentation group for {cls}: {exc}\")\n","/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'\n","  warnings.warn(f\"Could not get documentation group for {cls}: {exc}\")\n","GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.\n","GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.\n","GradioDeprecationWarning: Unknown style parameter: height\n","GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.\n","GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.\n","GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.\n","IMPORTANT: You are using gradio version 3.39.0, however version 4.29.0 is available, please upgrade.\n","--------\n","GradioDeprecationWarning: The `enable_queue` parameter has been deprecated. Please use the `.queue()` method instead.\n","Running on local URL:  http://127.0.0.1:7860\n","Running on public URL: https://db1c06c815fa1cb057.gradio.live\n","\n","This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)\n","get meta information of input video\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 125, in init_SegTracker_Stroke\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","get meta information of input video\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 282, in gd_detect\n","    Seg_Tracker, _ , _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Start tracking !\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 329, in tracking_objects\n","    return tracking_objects_in_video(Seg_Tracker, input_video, input_img_seq, fps, frame_num)\n","  File \"/content/drive/MyDrive/CEVI_Final/seg_track_anything.py\", line 98, in tracking_objects_in_video\n","    return video_type_input_tracking(SegTracker, input_video, io_args, video_name, frame_num)\n","  File \"/content/drive/MyDrive/CEVI_Final/seg_track_anything.py\", line 134, in video_type_input_tracking\n","    sam_gap = SegTracker.sam_gap\n","AttributeError: 'NoneType' object has no attribute 'sam_gap'\n","get meta information of input video\n","Click\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 215, in sam_click\n","    Seg_Tracker, _, _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Click\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 215, in sam_click\n","    Seg_Tracker, _, _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Click\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 215, in sam_click\n","    Seg_Tracker, _, _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 125, in init_SegTracker_Stroke\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Click\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 215, in sam_click\n","    Seg_Tracker, _, _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 282, in gd_detect\n","    Seg_Tracker, _ , _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","get meta information of input video\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/routes.py\", line 442, in run_predict\n","    output = await app.get_blocks().process_api(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1392, in process_api\n","    result = await self.call_function(\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 1097, in call_function\n","    prediction = await anyio.to_thread.run_sync(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py\", line 33, in run_sync\n","    return await get_asynclib().run_sync_in_worker_thread(\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 877, in run_sync_in_worker_thread\n","    return await future\n","  File \"/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py\", line 807, in run\n","    result = context.run(func, *args)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/utils.py\", line 703, in wrapper\n","    response = f(*args, **kwargs)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 282, in gd_detect\n","    Seg_Tracker, _ , _, _ = init_SegTracker(aot_model, long_term_mem, max_len_long_term, sam_gap, max_obj_num, points_per_side, origin_frame)\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 104, in init_SegTracker\n","    Seg_Tracker = SegTracker(segtracker_args, sam_args, aot_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/SegTracker.py\", line 19, in __init__\n","    self.sam = Segmentor(sam_args)\n","  File \"/content/drive/MyDrive/CEVI_Final/tool/segmentor.py\", line 15, in __init__\n","    self.sam = sam_model_registry[sam_args[\"model_type\"]](checkpoint=sam_args[\"sam_checkpoint\"])\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 38, in build_sam_vit_b\n","    return _build_sam(\n","  File \"/content/drive/MyDrive/CEVI_Final/sam/segment_anything/build_sam.py\", line 104, in _build_sam\n","    with open(checkpoint, \"rb\") as f:\n","FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/sam_vit_b_01ec64.pth'\n","Keyboard interruption in main thread... closing server.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 2133, in block_thread\n","    time.sleep(0.1)\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 1106, in <module>\n","    seg_track_app()\n","  File \"/content/drive/MyDrive/CEVI_Final/app.py\", line 1102, in seg_track_app\n","    app.launch(debug=True, enable_queue=True, share=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 2044, in launch\n","    self.block_thread()\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/blocks.py\", line 2137, in block_thread\n","    self.server.close()\n","  File \"/usr/local/lib/python3.10/dist-packages/gradio/networking.py\", line 49, in close\n","    self.thread.join()\n","  File \"/usr/lib/python3.10/threading.py\", line 1096, in join\n","    self._wait_for_tstate_lock()\n","  File \"/usr/lib/python3.10/threading.py\", line 1116, in _wait_for_tstate_lock\n","    if lock.acquire(block, timeout):\n","KeyboardInterrupt\n","Killing tunnel 127.0.0.1:7860 <> https://db1c06c815fa1cb057.gradio.live\n"]}],"source":["!python app.py"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"XvXG3UDRiiih"},"outputs":[],"source":["\\"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"feHtwtfujpwK"},"outputs":[],"source":[]}],"metadata":{"accelerator":"GPU","colab":{"provenance":[],"mount_file_id":"1IyZdKkgZvMVxppnPNI72LLVRAlhkxhfA","authorship_tag":"ABX9TyMnUysFnFCmScK7cbV1cmUo"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}